language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.1
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
script:
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report